@baseUrl=http://localhost:3000
@apiUrl={{baseUrl}}/api/v1
@linkId={{$dotenv LINK_ID}}

###
GET {{baseUrl}} HTTP/1.1

###
GET {{baseUrl}}/metrics HTTP/1.1

###
# @no-redirect
GET {{baseUrl}}/{{linkId}}?utm_source=source_{{$randomInt 0 9}}&utm_medium=medium_{{$randomInt 0 9}}&utm_campaign=campaign_{{$randomInt 0 9}} HTTP/1.1

###
GET {{apiUrl}}/links/{{linkId}}

###
POST {{apiUrl}}/links HTTP/1.1
Content-Type: application/json
Origin: http://localhost:3000

{
    "link": {
        "targetUrl": "https://docs.sms-gate.app"
    }
}

###
GET {{apiUrl}}/links/{{linkId}}/stats

###
OPTIONS {{apiUrl}}/links/{{linkId}}/stats
Origin: http://localhost:3000
Access-Control-Request-Method: GET